fragment AboutFragment on AboutRecord {
	_createdAt
	id
	title
	slug
	intro(markdown: false)
	dropcap
	content {
		value
		blocks {
			__typename
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageFragment
				}
			}
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
				layout
			}
			... on LogoRecord {
				__typename
				id
				logotypes {
					...ImageFragment
				}
			}
			... on VideoRecord {
				__typename
				caption
				id
				video {
					width
					height
					provider
					providerUid
					thumbnailUrl
					title
					url
				}
			}
		}
	}
}
