fragment DistrictFragment on DistrictRecord {
	id
	name
	email
	subdomain
	color {
		hex
		red
		green
		blue
	}
	email
	facebook
	instagram
	intro(markdown: false)
	contentContact {
		value
		blocks {
			__typename
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageFragment
				}
			}
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
				layout
			}
			... on LogoRecord {
				__typename
				id
				image {
					...ImageFragment
				}
			}
			... on VideoRecord {
				__typename
				caption
				id
				video {
					width
					height
					provider
					providerUid
					thumbnailUrl
					title
					url
				}
			}
		}
	}
	content {
		__typename
		... on ImageShortcutRecord {
			__typename
			id
			image {
				...ImageFragment
			}
			headline
			text
			externalLink
			link {
				__typename
				... on AboutRecord {
					__typename
					slug
				}
				... on NewsRecord {
					__typename
					slug
				}
				... on ProjectRecord {
					__typename
					slug
				}
				... on ProjectSubpageRecord {
					__typename
					slug
					_allReferencingProjects {
						__typename
						slug
					}
				}
				... on ExternalLinkRecord {
					__typename
					url
					title
				}
			}
		}
		... on StartProjectRecord {
			__typename
			id
			projects {
				...ProjectFragmentLight
			}
		}
		... on StartSelectedNewsRecord {
			__typename
			id
			news {
				...NewsFragmentLight
			}
		}
		... on StartTextRecord {
			__typename
			text
		}
		... on StartImageGalleryRecord {
			__typename
			id
			links {
				... on ExternalLinkRecord {
					...ExternalLinkFragment
				}
				... on NewsRecord {
					...NewsFragmentLight
				}
				... on ProjectRecord {
					...ProjectFragmentLight
				}
			}
		}
		... on StartSelectedDistrictNewsRecord {
			__typename
		}
	}
}
