fragment ImageThumbnailFragment on ImageFileField {
	id
	mimeType
	url
	title
	alt
	height
	width
	responsiveImage(
		imgixParams: { q: 70, ar: "6:4", fit: crop, auto: format }
		sizes: "(max-width: 46.24em) 50vw, 25vw"
	) {
		src
		sizes
		width
		height
		alt
		title
		base64
		sizes
	}
}
