fragment ProjectFragmentLight on ProjectRecord {
	_createdAt
	_updatedAt
	id
	title
	subtitle
	slug
	intro(markdown: false)
	color {
		hex
	}
	colorOption
	completed
	district {
		...DistrictFragmentLight
	}
	subpage {
		...ProjectSubpageFragmentLight
	}
	image {
		...ImageFragment
	}
}
