fragment ProjectFragment on ProjectRecord {
	id
	title
	subtitle
	slug
	_createdAt
	intro(markdown: false)
	color {
		hex
	}
	colorOption
	completed
	webpage
	district {
		...DistrictFragmentLight
	}
	image {
		...ImageFragment
	}
	subpage {
		...ProjectSubpageFragmentLight
	}
	dropcap
	content {
		value
		blocks {
			__typename
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on DownloadPdfRecord {
				__typename
				id
				url
				text
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageFragment
				}
			}
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
				layout
			}
			... on LogoRecord {
				__typename
				id
				logotypes {
					...ImageMediumFragment
				}
			}
			... on VideoRecord {
				__typename
				caption
				id
				video {
					width
					height
					provider
					providerUid
					thumbnailUrl
					title
					url
				}
			}
		}
	}
}
