query AllAbouts($first: IntType = 100, $skip: IntType = 0) {
	abouts: allAbouts(first: $first, skip: $skip, orderBy: [_createdAt_DESC]) {
		...AboutFragment
	}
	pagination: _allAboutsMeta {
		count
	}
}

query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}
