query AllDistrics {
	districts: allDistricts(first: 100, orderBy: name_ASC) {
		...DistrictFragmentLight
	}
}

query District($districtId: ItemId) {
	district(filter: { id: { eq: $districtId } }) {
		...DistrictFragment
	}
}

query DistrictBySubdomain($subdomain: String) {
	district(filter: { subdomain: { eq: $subdomain } }) {
		...DistrictFragment
	}
}
