query AllDistrics {
	districts: allDistricts(first: 100, orderBy: name_ASC) {
		...DistrictFragment
	}
}
query District($subdomain: String!) {
	district(filter: { subdomain: { eq: $subdomain } }) {
		...DistrictFragment
	}
}
