query Menu($districtId: ItemId) {
	allAbouts(filter: { district: { eq: $districtId } }, first: 100, orderBy: position_ASC) {
		id
		slug
		title
	}
	allProjects(
		filter: { district: { eq: $districtId } }
		first: 4
		orderBy: _createdAt_DESC
	) {
		id
		slug
		title
	}
	allNews(filter: { district: { eq: $districtId } }, first: 4, orderBy: _createdAt_DESC) {
		id
		slug
		title
	}
	allDistricts(first: 100, orderBy: name_ASC) {
		id
		subdomain
		facebook
		instagram
		name
	}
}
