query SiteSearch(
	$aboutIds: [ItemId]
	$newsIds: [ItemId]
	$projectIds: [ItemId]
	$first: IntType = 100
	$skip: IntType = 0
	$locale: SiteLocale
	$districtId: ItemId
) {
	allAbouts(
		first: $first
		skip: $skip
		locale: $locale
		filter: { id: { in: $aboutIds }, district: { eq: $districtId } }
	) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
		district {
			id
			subdomain
		}
	}
	allNews(
		first: $first
		skip: $skip
		locale: $locale
		filter: { id: { in: $newsIds }, district: { eq: $districtId } }
	) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
		district {
			id
			subdomain
		}
	}
	allProjects(
		first: $first
		skip: $skip
		locale: $locale
		filter: { id: { in: $projectIds }, district: { eq: $districtId } }
	) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
		district {
			id
			subdomain
		}
	}
	allProjectSubpages(
		first: $first
		skip: $skip
		locale: $locale
		filter: { id: { in: $projectIds }, district: { eq: $districtId } }
	) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
		district {
			id
			subdomain
		}
	}
}
