query Sitemap($districtId: ItemId!, $first: IntType!, $skip: IntType!) {
	allAbouts(filter: { district: { eq: $districtId } }, first: $first, skip: $skip) {
		_modelApiKey
		id
		slug
		title
		_updatedAt
	}
	_allAboutsMeta(filter: { district: { eq: $districtId } }) {
		count
	}
	allNews(filter: { district: { eq: $districtId } }, first: $first) {
		_modelApiKey
		id
		slug
		title
		_updatedAt
	}
	_allNewsMeta(filter: { district: { eq: $districtId } }) {
		count
	}
	allProjects(filter: { district: { eq: $districtId } }, first: $first, skip: $skip) {
		_modelApiKey
		id
		slug
		title
		_updatedAt
		subpage {
			_modelApiKey
			id
			slug
			title
			_updatedAt
		}
	}
	_allProjectsMeta(filter: { district: { eq: $districtId } }) {
		count
	}
}
