query Start($districtId: ItemId) {
	start {
		id
		selectedInDistricts {
			__typename
			... on NewsRecord {
				__typename
				...NewsFragmentLight
			}
			... on ProjectRecord {
				__typename
				...ProjectFragmentLight
			}
		}
	}
	latestNews: allNews(
		filter: { district: { eq: $districtId } }
		first: 4
		orderBy: [_createdAt_DESC]
	) {
		...NewsFragmentLight
	}
	district(filter: { id: { eq: $districtId } }) {
		...DistrictFragment
	}
}
